name: powershell-preview-scheduler

on:
  schedule:
    - cron: '0 0,12 * * 1-5'
  workflow_dispatch:

env:
  SNAP_NAME: powershell-preview
  SNAP_DIR: powershell-preview

jobs:
  needs-store-publishing:
    runs-on: ubuntu-latest
    outputs:
      needs-publishing: ${{ steps.check.outputs.needs-publishing }}
    steps:
      - uses: actions/checkout@v4
        id: checkout
      - name: Check if Snap Store has latest version
        id: check
        shell: bash
        run: |
          if ./eng/compare-store-buildinfo-versions.py --snap-name $SNAP_NAME --snap-channel latest/edge --buildinfo-url $(cat ${SNAP_DIR}/buildinfo-url); then
            echo "Needs publishing"
            echo "needs-publishing=true" >> $GITHUB_OUTPUT
          else
            echo "Does not need publishing"
            echo "needs-publishing=false" >> $GITHUB_OUTPUT
          fi
  build:
    uses: ./.github/workflows/template-build.yaml
    needs: needs-store-publishing
    if: ${{ needs.needs-store-publishing.outputs.needs-publishing == 'true' }}
    with:
      release: 'preview'
  publish:
    uses: ./.github/workflows/template-publish.yaml
    needs: build
    with:
      release: 'preview'
