name: powershell-preview

on:
  push:
    branches: main
    paths:
      - 'powershell-preview/**'
  pull_request:
    branches: main
    paths:
      - 'powershell-preview/**'
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/template-build.yaml
    with:
      release: 'preview'
  publish:
    uses: ./.github/workflows/template-publish.yaml
    needs: build
    if: ${{ contains(fromJSON('["push", "workflow_dispatch"]'), github.event_name) && github.ref_name == 'main' }}
    with:
      release: 'preview'
    secrets:
      SNAP_STORE_TOKEN: ${{ secrets.SNAP_STORE_TOKEN }}
